"""Katalog: 20 faoliyat yo'nalishi (kelishilgan tartibda) va ularning faoliyat turlari."""

CATALOG = [
    {"name": "Savdo", "ic": "🛒",
     "t": ["Oziq-ovqat do'koni", "Kiyim-kechak", "Poyabzal", "Elektronika", "Maishiy texnika", "Telefon va aksessuar", "Qurilish mollari", "Mebel do'koni", "Uy jihozlari", "Dorixona", "Optika", "Parfyumeriya va kosmetika", "Zargarlik", "Bolalar mollari", "Kanselyariya", "Gullar do'koni", "Sport mollari", "Kitob do'koni", "Avtoehtiyot qismlar", "Bozor rastasi"]},
    {"name": "Transport va logistika", "ic": "🚕",
     "t": ["Taxi", "Yo'lovchi tashish", "Yuk tashish", "Yetkazib berish", "Kuryer xizmati", "Evakuator", "Avto ijara", "Ombor xizmati", "Konteyner tashish", "Refrijerator tashish"]},
    {"name": "Xizmat ko'rsatish", "ic": "🧰",
     "t": ["Kunlik ishchi", "Uy tozalash", "Santexnik", "Elektrik", "Konditsioner ta'miri", "Muzlatgich ta'miri", "Kir yuvish mashinasi ta'miri", "Kompyuter ta'miri", "Telefon ta'miri", "Payvandchi", "Bo'yoqchi", "Mebel yig'uvchi", "Eshik-deraza ustasi", "Uy ko'chirish", "Bog'bon"]},
    {"name": "Maishiy xizmatlar", "ic": "💇",
     "t": ["Sartaroshxona", "Go'zallik saloni", "Manikur-pedikur", "Kosmetolog", "Massaj", "Qosh-kiprik", "Makiyaj ustasi", "Tikuvchilik", "Poyabzal ta'miri", "Kimyoviy tozalash", "Solaryum", "Hammom va sauna"]},
    {"name": "Umumiy ovqatlanish", "ic": "🍽️",
     "t": ["Kafe", "Restoran", "Fast-food", "Milliy taomlar", "Choyxona", "Pitseriya", "Sushi bar", "Kofeynya", "Nonvoyxona", "Qandolatxona", "Oshxona", "Yetkazib beruvchi oshxona"]},
    {"name": "Qurilish", "ic": "🏗️",
     "t": ["Quruvchi brigada", "Ta'mirlash (remont)", "Montaj ishlari", "Loyihalash", "Tom yopish", "Beton quyish", "Gips-karton", "Kafel-plitka", "Elektromontaj", "Santexmontaj", "Fasad ishlari", "Landshaft dizayni", "Quduq qazish"]},
    {"name": "Tibbiy xizmatlar", "ic": "🩺",
     "t": ["Klinika", "Stomatologiya", "Laboratoriya", "Shifokor konsultatsiyasi", "Hamshira xizmati", "Ginekologiya", "Pediatriya", "UZI diagnostika", "Fizioterapiya", "Oftalmologiya", "Massaj kabineti", "Veterinariya"]},
    {"name": "Ta'lim faoliyati", "ic": "📚",
     "t": ["O'quv markazi", "Repetitor", "Til kurslari", "IT kurslari", "Avtomaktab", "Musiqa maktabi", "Sport maktabi", "Rassomlik", "Xoreografiya", "Bog'cha", "Onlayn kurslar", "Imtihonga tayyorlash"]},
    {"name": "Ko'chmas mulk", "ic": "🏢",
     "t": ["Rieltor", "Kvartira sotish", "Uy sotish", "Yer uchastkasi", "Ijaraga berish", "Tijorat ko'chmas mulki", "Bino boshqaruvi", "Baholash xizmati"]},
    {"name": "Qishloq xo'jaligi", "ic": "🌾",
     "t": ["Dehqonchilik", "Chorvachilik", "Parrandachilik", "Asalarichilik", "Bog'dorchilik", "Issiqxona", "Baliqchilik", "Urug' va ko'chat", "Em-xashak", "Sut mahsulotlari"]},
    {"name": "Axborot texnologiyalari", "ic": "💻",
     "t": ["Dasturlash", "Veb-sayt yaratish", "Mobil ilova", "Grafik dizayn", "SMM", "1C dasturlash", "Kompyuter tarmoqlari", "Kiberxavfsizlik", "Video montaj", "IT xizmat"]},
    {"name": "Konsalting va professional", "ic": "⚖️",
     "t": ["Advokat", "Yuridik maslahat", "Buxgalteriya", "Soliq maslahati", "Audit", "Notarius", "Tarjimon", "Biznes-reja", "HR xizmati", "Litsenziya olish"]},
    {"name": "Madaniyat, sport, ko'ngilochar", "ic": "🏟️",
     "t": ["Sport zali", "Fitnes klub", "Suzish havzasi", "Bilyard", "Bouling", "Kvest xona", "Foto-video", "To'yxona", "Tadbir tashkil etish", "DJ xizmati", "Tamada", "Sharlar bilan bezash"]},
    {"name": "Turizm va mehmonxona", "ic": "🏨",
     "t": ["Mehmonxona", "Hostel", "Kvartira sutkalik", "Dam olish maskani", "Sanatoriy", "Turagentlik", "Ekskursiya", "Aviachipta", "Viza xizmati"]},
    {"name": "Ishlab chiqarish", "ic": "🏭",
     "t": ["Oziq-ovqat ishlab chiqarish", "Mebel", "Tikuv sexi", "Metall konstruksiyalar", "Plastik buyumlar", "Qurilish materiallari", "Ichimliklar", "Qadoqlash", "Oyna-deraza"]},
    {"name": "Hunarmandchilik", "ic": "🧵",
     "t": ["Yog'och buyumlar", "Charm buyumlar", "Kulolchilik", "Kashtachilik", "Zardo'zlik", "Gilamdo'zlik", "Milliy liboslar", "Suvenir", "Qo'lda yasalgan buyumlar"]},
    {"name": "Reklama va marketing", "ic": "📣",
     "t": ["SMM", "Targetolog", "Kontekst reklama", "Banner va dizayn", "Kontent yaratish", "Blogger reklama", "Reklama agentligi"]},
    {"name": "Poligrafiya va nashriyot", "ic": "🖨️",
     "t": ["Chop etish", "Vizitka va buklet", "Banner bosish", "Muhr-tamg'a", "Stiker", "Futbolkaga bosish", "Lazer o'yish", "Kitob nashri", "Kalendar"]},
    {"name": "Moliyaviy faoliyat", "ic": "💳",
     "t": ["Sug'urta", "Mikroqarz", "Pul o'tkazmalari", "Valyuta ayirboshlash", "Lizing", "Kredit maslahati", "Investitsiya maslahati"]},
    {"name": "Import-eksport", "ic": "🚢",
     "t": ["Import", "Eksport", "Bojxona vositachiligi", "Xalqaro logistika", "Sertifikatlash", "Tashqi savdo maslahati"]},
]

# E'lon toifalari
LISTING_CATS = [
    {"key": "uy", "name": "Uy-joy", "ic": "🏠"},
    {"key": "ish", "name": "Ish o'rinlari", "ic": "💼"},
    {"key": "moshina", "name": "Moshinalar", "ic": "🚙"},
    {"key": "hayvon", "name": "Hayvonlar", "ic": "🐾"},
    {"key": "texnika", "name": "Texnika", "ic": "📱"},
    {"key": "boshqa", "name": "Boshqalar", "ic": "📦"},
]
